config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  resources :product_variants
  resources :variants
  devise_for :users
  devise_for :admins
  root to: "home#index"

  authenticate :admin do
    resources :products
    resources :categories
  end

  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :variant
  belongs_to :product
end

app/controllers/product_variants_controller.rb
class ProductVariantsController < ApplicationController
  before_action :set_product_variant, only: [:show, :edit, :update, :destroy]

  # GET /product_variants
  # GET /product_variants.json
  def index
    @product_variants = ProductVariant.all
  end

  # GET /product_variants/1
  # GET /product_variants/1.json
  def show
  end

  # GET /product_variants/new
  def new
    @product_variant = ProductVariant.new
  end

  # GET /product_variants/1/edit
  def edit
  end

  # POST /product_variants
  # POST /product_variants.json
  def create
    @product_variant = ProductVariant.new(product_variant_params)

    respond_to do |format|
      if @product_variant.save
        format.html { redirect_to @product_variant, notice: 'Product variant was successfully created.' }
        format.json { render :show, status: :created, location: @product_variant }
      else
        format.html { render :new }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_variants/1
  # PATCH/PUT /product_variants/1.json
  def update
    respond_to do |format|
      if @product_variant.update(product_variant_params)
        format.html { redirect_to @product_variant, notice: 'Product variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_variant }
      else
        format.html { render :edit }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_variants/1
  # DELETE /product_variants/1.json
  def destroy
    @product_variant.destroy
    respond_to do |format|
      format.html { redirect_to product_variants_url, notice: 'Product variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_variant
      @product_variant = ProductVariant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_variant_params
      params.require(:product_variant).permit(:variant_id, :product_id)
    end
end

app/helpers/product_variants_helper.rb
module ProductVariantsHelper
end

app/views/product_variants/_form.html.erb
<%= form_with(model: product_variant, local: true) do |form| %>
  <% if product_variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_variant.errors.count, "error") %> prohibited this product_variant from being saved:</h2>

      <ul>
      <% product_variant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :variant_id %>
    <%= form.text_field :variant_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_variants/edit.html.erb
<h1>Editing Product Variant</h1>

<%= render 'form', product_variant: @product_variant %>

<%= link_to 'Show', @product_variant %> |
<%= link_to 'Back', product_variants_path %>

app/views/product_variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Variants</h1>

<table>
  <thead>
    <tr>
      <th>Variant</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_variants.each do |product_variant| %>
      <tr>
        <td><%= product_variant.variant %></td>
        <td><%= product_variant.product %></td>
        <td><%= link_to 'Show', product_variant %></td>
        <td><%= link_to 'Edit', edit_product_variant_path(product_variant) %></td>
        <td><%= link_to 'Destroy', product_variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Variant', new_product_variant_path %>

app/views/product_variants/new.html.erb
<h1>New Product Variant</h1>

<%= render 'form', product_variant: @product_variant %>

<%= link_to 'Back', product_variants_path %>

app/views/product_variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Variant:</strong>
  <%= @product_variant.variant %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_variant.product %>
</p>

<%= link_to 'Edit', edit_product_variant_path(@product_variant) %> |
<%= link_to 'Back', product_variants_path %>